"""p3_content_blocks

Revision ID: 8e00e6ab7107
Revises: 8bd66b09017c
Create Date: 2026-04-30 16:43:15.890430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e00e6ab7107'
down_revision: Union[str, None] = '8bd66b09017c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ops_content_blocks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('locale', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('draft_body', sa.String(), nullable=True),
    sa.Column('draft_edited_by', sa.Integer(), nullable=True),
    sa.Column('draft_edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_body', sa.String(), nullable=True),
    sa.Column('published_version', sa.Integer(), nullable=False),
    sa.Column('published_by', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('review_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['draft_edited_by'], ['ops_users.id'], ),
    sa.ForeignKeyConstraint(['published_by'], ['ops_users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['ops_users.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['ops_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'key', 'locale', name='uq_block_section_key_locale')
    )
    op.create_index('ix_block_status', 'ops_content_blocks', ['status'], unique=False)
    op.create_table('ops_content_block_versions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('block_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('edited_by', sa.Integer(), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['ops_content_blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['edited_by'], ['ops_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id', 'version', name='uq_block_version')
    )
    op.create_index('ix_block_version_block', 'ops_content_block_versions', ['block_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_block_version_block', table_name='ops_content_block_versions')
    op.drop_table('ops_content_block_versions')
    op.drop_index('ix_block_status', table_name='ops_content_blocks')
    op.drop_table('ops_content_blocks')
    # ### end Alembic commands ###
