"""p4_device_codes

Revision ID: 1bd3e01cab2b
Revises: 8e00e6ab7107
Create Date: 2026-04-30 17:01:51.238083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bd3e01cab2b'
down_revision: Union[str, None] = '8e00e6ab7107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ops_device_codes',
    sa.Column('device_code', sa.String(), nullable=False),
    sa.Column('user_code', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_label', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['ops_users.id'], ),
    sa.PrimaryKeyConstraint('device_code'),
    sa.UniqueConstraint('user_code')
    )
    op.create_index('ix_device_user_code', 'ops_device_codes', ['user_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_device_user_code', table_name='ops_device_codes')
    op.drop_table('ops_device_codes')
    # ### end Alembic commands ###
