"""p2_change_requests

Revision ID: 8bd66b09017c
Revises: b7c40ca6ba0c
Create Date: 2026-04-30 15:31:19.580994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8bd66b09017c'
down_revision: Union[str, None] = 'b7c40ca6ba0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ops_change_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description_md', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('github_issue_url', sa.String(), nullable=True),
    sa.Column('github_issue_number', sa.Integer(), nullable=True),
    sa.Column('github_pr_url', sa.String(), nullable=True),
    sa.Column('github_pr_number', sa.Integer(), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['ops_users.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['ops_sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cr_requester', 'ops_change_requests', ['requester_id'], unique=False)
    op.create_index('ix_cr_section', 'ops_change_requests', ['section_id'], unique=False)
    op.create_table('ops_change_request_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('github_event_id', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['ops_change_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cr_event_github_id', 'ops_change_request_events', ['github_event_id'], unique=False)
    op.create_index('ix_cr_event_request', 'ops_change_request_events', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cr_event_request', table_name='ops_change_request_events')
    op.drop_index('ix_cr_event_github_id', table_name='ops_change_request_events')
    op.drop_table('ops_change_request_events')
    op.drop_index('ix_cr_section', table_name='ops_change_requests')
    op.drop_index('ix_cr_requester', table_name='ops_change_requests')
    op.drop_table('ops_change_requests')
    # ### end Alembic commands ###
