"""p1_ops_permissions_health_alerts

Revision ID: b7c40ca6ba0c
Revises: 3999387200e6
Create Date: 2026-04-30 15:10:48.247628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7c40ca6ba0c'
down_revision: Union[str, None] = '3999387200e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ops_alert_state',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('last_alerted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('resolved_notified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['ops_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.create_table('ops_health_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['ops_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_health_section_time', 'ops_health_snapshots', ['section_id', 'checked_at'], unique=False)
    op.create_table('ops_section_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('can_edit_content', sa.Boolean(), nullable=False),
    sa.Column('can_open_pr', sa.Boolean(), nullable=False),
    sa.Column('can_publish', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['ops_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['ops_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'user_id', name='uq_perm_section_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ops_section_permissions')
    op.drop_index('ix_health_section_time', table_name='ops_health_snapshots')
    op.drop_table('ops_health_snapshots')
    op.drop_table('ops_alert_state')
    # ### end Alembic commands ###
